
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module QSFP_4PORT(

           //////////// CLOCK //////////
           input 		          		CLKUSR_100,
           input 		          		CLK_100_B3D,
           input 		          		CLK_50_B2J,
           input 		          		CLK_50_B2L,
           input 		          		CLK_50_B3D,
           input 		          		CLK_50_B3F,
           input 		          		CLK_50_B3H,

           //////////// KEY //////////
           input 		     [3:0]		BUTTON,
           input 		          		CPU_RESET_n,

           //////////// LED //////////
           output		     [3:0]		LED,
           output		     [3:0]		LED_BRACKET,

           //////////// SI5340A //////////
           output		          		SI5340A_I2C_SCL,
           inout 		          		SI5340A_I2C_SDA,
           input 		          		SI5340A_INTR,
           output		          		SI5340A_OE_n,
           output		          		SI5340A_RST_n,

           //////////// TPS40428 //////////
           input 		          		TPS40428_ALERT,
           output		          		TPS40428_CLK,
           inout 		          		TPS40428_DATA,

           //////////// QSFPA //////////
           input 		          		QSFPA_INTERRUPT_n,
           output		          		QSFPA_LP_MODE,
           input 		          		QSFPA_MOD_PRS_n,
           output		          		QSFPA_MOD_SEL_n,
           input 		          		QSFPA_REFCLK_p,
           output		          		QSFPA_RST_n,
           input 		     [3:0]		QSFPA_RX_p,
           output		          		QSFPA_SCL,
           inout 		          		QSFPA_SDA,
           output		     [3:0]		QSFPA_TX_p,

           //////////// QSFPB //////////
           input 		          		QSFPB_INTERRUPT_n,
           output		          		QSFPB_LP_MODE,
           input 		          		QSFPB_MOD_PRS_n,
           output		          		QSFPB_MOD_SEL_n,
           input 		          		QSFPB_REFCLK_p,
           output		          		QSFPB_RST_n,
           input 		     [3:0]		QSFPB_RX_p,
           output		          		QSFPB_SCL,
           inout 		          		QSFPB_SDA,
           output		     [3:0]		QSFPB_TX_p,

           //////////// QSFPC //////////
           input 		          		QSFPC_INTERRUPT_n,
           output		          		QSFPC_LP_MODE,
           input 		          		QSFPC_MOD_PRS_n,
           output		          		QSFPC_MOD_SEL_n,
           input 		          		QSFPC_REFCLK_p,
           output		          		QSFPC_RST_n,
           input 		     [3:0]		QSFPC_RX_p,
           output		          		QSFPC_SCL,
           inout 		          		QSFPC_SDA,
           output		     [3:0]		QSFPC_TX_p,

           //////////// QSFPD //////////
           input 		          		QSFPD_INTERRUPT_n,
           output		          		QSFPD_LP_MODE,
           input 		          		QSFPD_MOD_PRS_n,
           output		          		QSFPD_MOD_SEL_n,
           input 		          		QSFPD_REFCLK_p,
           output		          		QSFPD_RST_n,
           input 		     [3:0]		QSFPD_RX_p,
           output		          		QSFPD_SCL,
           inout 		          		QSFPD_SDA,
           output		     [3:0]		QSFPD_TX_p
       );



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================




//=======================================================
//  Configure SI5340A
//=======================================================
`define SI5340A_POWER_DOWN  3'd0
`define SI5340A_644M53125   3'd1
`define SI5340A_322M265625  3'd2
`define SI5340A_312M5       3'd3
`define SI5340A_250M        3'd4
`define SI5340A_156M25      3'd5
`define SI5340A_125M        3'd6
`define SI5340A_100M        3'd7

wire si5340a_controller_start, si5340a_ready;
assign si5340a_controller_start = ~BUTTON[0];

si5340a_controller si5340a_controller(
                       .iCLK(CLK_50_B2J),
                       .iRST_n(CPU_RESET_n),
                       .iStart(si5340a_controller_start),
                       .iPLL_OUT0_FREQ_SEL(`SI5340A_644M53125),//QSFP-A
                       .iPLL_OUT1_FREQ_SEL(`SI5340A_644M53125),//QSFP-B
                       .iPLL_OUT2_FREQ_SEL(`SI5340A_644M53125),//QSFP-C
                       .iPLL_OUT3_FREQ_SEL(`SI5340A_644M53125),//QSFP-D
                       .I2C_CLK(SI5340A_I2C_SCL),
                       .I2C_DATA(SI5340A_I2C_SDA),
                       .oPLL_REG_CONFIG_DONE(si5340a_ready)
                   );

assign SI5340A_OE_n = 1'b0;
assign SI5340A_RST_n = CPU_RESET_n;

// =======================================================
// ATX PLL for QSFP B
// =======================================================
wire tx_serial_clk_b_w;
wire pll_locked_b_w;
ATX_PLL ATX_PLL_B (
            .pll_powerdown (1'b0),
            .pll_refclk0   (QSFPB_REFCLK_p),        // 改吃 B 埠專屬的參考時脈
            .tx_serial_clk (tx_serial_clk_b_w),     // B 埠專屬的發射時脈
            .pll_locked    (pll_locked_b_w),
            .pll_cal_busy  ()
        );

// =======================================================
// ATX PLL for QSFP C
// =======================================================
wire tx_serial_clk_c_w;
wire pll_locked_c_w;
ATX_PLL ATX_PLL_C (
            .pll_powerdown (1'b0),
            .pll_refclk0   (QSFPC_REFCLK_p),        // 改吃 C 埠專屬的參考時脈
            .tx_serial_clk (tx_serial_clk_c_w),     // C 埠專屬的發射時脈
            .pll_locked    (pll_locked_c_w),
            .pll_cal_busy  ()
        );

// =======================================================
// PHY_RST
// =======================================================
wire global_reset_w = ~BUTTON[1] | ~si5340a_ready;
wire tx_analogreset_w, tx_digitalreset_w;
wire rx_analogreset_w, rx_digitalreset_w;
wire tx_cal_busy_w, rx_cal_busy_w;
wire tx_ready_w, rx_ready_w;
wire rx_is_lockedtodata_w;
PHY_RESET PHY_RESET (
              .clock              (CLK_50_B2J),           // i, 使用基本clk (50MHz)
              .reset              (global_reset_w),       // i, 全域重置輸入，啟動重置流程
              .pll_powerdown      (),                     // o, 輸出給 ATX_PLL 的重置訊號
              .tx_analogreset     (tx_analogreset_w),     // o, 輸出給 PHY 發送端類比電路重置
              .tx_digitalreset    (tx_digitalreset_w),    // o, 輸出給 PHY 發送端數位電路重置
              .tx_ready           (tx_ready_w),                     // o, 通知系統：發送端已準備就緒
              .pll_locked         (pll_locked_b_w && pll_locked_c_w),         // i, 接收 ATX_PLL 的鎖定狀態
              .pll_select         (1'b0),                 // i, 選擇要監控哪一組 PLL (通常接常數)
              .tx_cal_busy        (tx_cal_busy_w),        // i, 接收 PHY 發送端的校準忙碌狀態
              .rx_analogreset     (rx_analogreset_w),     // o, 輸出給 PHY 接收端類比電路重置
              .rx_digitalreset    (rx_digitalreset_w),    // o, 輸出給 PHY 接收端數位電路重置
              .rx_ready           (rx_ready_w),                     // o, 通知系統：接收端已準備就緒
              .rx_is_lockedtodata (rx_is_lockedtodata_w), // i, 接收 PHY 的 CDR 資料鎖定狀態
              .rx_cal_busy        (rx_cal_busy_w)         // i, 接收 PHY 接收端的校準忙碌狀態
          );

// =======================================================
// PHY
// =======================================================
assign QSFPA_LP_MODE = 1'b0;
assign QSFPA_MOD_SEL_n = 1'b0;
assign QSFPA_RST_n = 1'b1;
assign QSFPB_LP_MODE = 1'b0;
assign QSFPB_MOD_SEL_n = 1'b0;
assign QSFPB_RST_n = 1'b1;
assign QSFPC_LP_MODE = 1'b0;
assign QSFPC_MOD_SEL_n = 1'b0;
assign QSFPC_RST_n = 1'b1;
assign QSFPD_LP_MODE = 1'b0;
assign QSFPD_MOD_SEL_n = 1'b0;
assign QSFPD_RST_n = 1'b1;

wire [3:0] phy_tx_cal_busy_w, phy_rx_cal_busy_w;
assign tx_cal_busy_w = |phy_tx_cal_busy_w;
assign rx_cal_busy_w = |phy_rx_cal_busy_w;

wire [3:0] phy_rx_is_lockedtodata_w;
assign rx_is_lockedtodata_w = &phy_rx_is_lockedtodata_w;

wire [3:0] phy_tx_clkout_w, phy_rx_clkout_w;    // 除頻後的clk, 使用這個去接收 64bit 資料

reg [63:0] phy_tx_parallel_data_r[0:3], phy_tx_parallel_data_w[0:3];
reg [3:0] phy_tx_enh_data_valid_r, phy_tx_enh_data_valid_w;
reg [1:0] phy_tx_control_r[0:3], phy_tx_control_w[0:3];
wire [3:0] phy_tx_enh_fifo_pfull_w;

wire [63:0] phy_rx_parallel_data_w[0:3];
wire [3:0] phy_rx_enh_data_valid_w;
reg [63:0] phy_rx_parallel_data_r[0:3];

// B 打出去，C 收回來
PHY PHY (
        .tx_analogreset          ({4{tx_analogreset_w}}),
        .tx_digitalreset         ({4{tx_digitalreset_w}}),
        .rx_analogreset          ({4{rx_analogreset_w}}),
        .rx_digitalreset         ({4{rx_digitalreset_w}}),
        .tx_cal_busy             (phy_tx_cal_busy_w),
        .rx_cal_busy             (),
        .tx_serial_clk0          ({4{tx_serial_clk_b_w}}),    // 吃 ATX_PLL 產生的 5156.25 MHz clk 當作發送端的串行時脈
        .rx_cdr_refclk0          (QSFPB_REFCLK_p),    // 吃 Si5340A 產生的 644.53125 MHz clk 當作 CDR 的參考時脈
        .tx_serial_data          (QSFPB_TX_p),
        .rx_serial_data          (QSFPB_RX_p),
        .rx_is_lockedtoref       (),
        .rx_is_lockedtodata      (),
        .tx_coreclkin            (phy_tx_clkout_w),
        .rx_coreclkin            (),
        .tx_clkout               (phy_tx_clkout_w),
        .rx_clkout               (),
        .tx_parallel_data        ({phy_tx_parallel_data_r[3], phy_tx_parallel_data_r[2], phy_tx_parallel_data_r[1], phy_tx_parallel_data_r[0]}),    //
        .rx_parallel_data        (),
        .tx_control              ({phy_tx_control_r[3], phy_tx_control_r[2], phy_tx_control_r[1], phy_tx_control_r[0]}),
        .rx_control              (),
        .tx_enh_data_valid       (phy_tx_enh_data_valid_r),
        .unused_tx_parallel_data (),
        .unused_rx_parallel_data (),
        .rx_seriallpbken         (4'b0000),    // 是否繞回主版
        .unused_tx_control       (),
        .unused_rx_control       (),
        .rx_enh_data_valid       (),
        .rx_enh_fifo_full        (),
        .tx_enh_fifo_full        (),
        .tx_enh_fifo_pfull       (phy_tx_enh_fifo_pfull_w),
        .rx_enh_fifo_rd_en       ()
    );


PHY PHY_C (
        .tx_analogreset          ({4{tx_analogreset_w}}),
        .tx_digitalreset         ({4{tx_digitalreset_w}}),
        .rx_analogreset          ({4{rx_analogreset_w}}),
        .rx_digitalreset         ({4{rx_digitalreset_w}}),
        .tx_cal_busy             (),
        .rx_cal_busy             (phy_rx_cal_busy_w),
        .tx_serial_clk0          ({4{tx_serial_clk_c_w}}),    // 吃 ATX_PLL 產生的 5156.25 MHz clk 當作發送端的串行時脈
        .rx_cdr_refclk0          (QSFPC_REFCLK_p),    // 吃 Si5340A 產生的 644.53125 MHz clk 當作 CDR 的參考時脈
        .tx_serial_data          (QSFPC_TX_p),
        .rx_serial_data          (QSFPC_RX_p),
        .rx_is_lockedtoref       (),
        .rx_is_lockedtodata      (phy_rx_is_lockedtodata_w),
        .tx_coreclkin            (),
        .rx_coreclkin            (phy_rx_clkout_w),
        .tx_clkout               (),
        .rx_clkout               (phy_rx_clkout_w),
        .tx_parallel_data        (),
        .rx_parallel_data        ({phy_rx_parallel_data_w[3], phy_rx_parallel_data_w[2], phy_rx_parallel_data_w[1], phy_rx_parallel_data_w[0]}),    //
        .tx_control              (),
        .rx_control              (),
        .tx_enh_data_valid       (),
        .unused_tx_parallel_data (),
        .unused_rx_parallel_data (),
        .rx_seriallpbken         (4'b0000),    // 是否繞回主版
        .unused_tx_control       (),
        .unused_rx_control       (),
        .rx_enh_data_valid       (phy_rx_enh_data_valid_w),
        .rx_enh_fifo_full        (),
        .tx_enh_fifo_full        (),
        .tx_enh_fifo_pfull       (),
        .rx_enh_fifo_rd_en       (4'b1111)
    );



// ===================================================================
// Tx Sequential
// ===================================================================
integer i;
genvar j;
generate
    for (j = 0; j < 4; j = j + 1)
    begin : tx_seq
        always @(posedge phy_tx_clkout_w[j] or posedge tx_digitalreset_w)
        begin
            if (tx_digitalreset_w)
            begin
                phy_tx_parallel_data_r[j] <= 64'b0;
                phy_tx_enh_data_valid_r[j] <= 1'b0;
                phy_tx_control_r[j] <= 2'b00;
            end
            else
            begin
                phy_tx_parallel_data_r[j] <= phy_tx_parallel_data_w[j];
                phy_tx_enh_data_valid_r[j] <= phy_tx_enh_data_valid_w[j];
                phy_tx_control_r[j] <= phy_tx_control_w[j];
            end
        end
    end
endgenerate


// ===================================================================
// Tx comb
// ===================================================================
always @(*)
begin
    // default
    for (i = 0; i < 4; i = i + 1)
    begin
        phy_tx_parallel_data_w[i] = phy_tx_parallel_data_r[i];
        phy_tx_control_w[i] = 2'b10;
        phy_tx_enh_data_valid_w[i] = 1'b0;
    end

    // Sending
    if (tx_digitalreset_w == 1'b0 && tx_ready_w == 1'b1)
    begin
        for (i = 0; i < 4; i = i + 1)
        begin
            if (phy_tx_enh_fifo_pfull_w[i] == 1'b1)
            begin
                phy_tx_enh_data_valid_w[i] = 1'b0;  // 暫停寫入，讓 PHY 補 Header
                phy_tx_control_w[i] = 2'b10;
                phy_tx_parallel_data_w[i] = phy_tx_parallel_data_r[i]; // 資料扣住不變，等待下個 cycle
            end
            else
            begin
                phy_tx_enh_data_valid_w[i] = 1'b1;  // 正常寫入
                phy_tx_control_w[i] = 2'b01;        // Data
                phy_tx_parallel_data_w[i] = phy_tx_parallel_data_r[i] + (i+1);
            end
        end
    end
end

// ==================================================================
// Rx Sequential
// ==================================================================
reg [26:0] cnt_ref_r;
reg [26:0] cnt_data_r[0:3], cnt_data_w[0:3];
generate
    for (j = 0; j < 4; j = j + 1)
    begin : rx_seq
        always @(posedge phy_rx_clkout_w[j] or posedge rx_digitalreset_w)
        begin
            if (rx_digitalreset_w)
            begin
                if (j == 0)
                    cnt_ref_r <= 27'b0;
                cnt_data_r[j] <= 27'b0;
                phy_rx_parallel_data_r[j] <= 64'b0;
                // phy_rx_control_r[j] <= 8'b0;
            end
            else
            begin
                if (j == 0)
                    cnt_ref_r <= cnt_ref_r +1;
                cnt_data_r[j] <= cnt_data_w[j];
                // phy_rx_control_r[j] <= phy_rx_control_w[j];
                if (phy_rx_enh_data_valid_w[j] == 1'b1)
                    phy_rx_parallel_data_r[j] <= phy_rx_parallel_data_w[j];

            end
        end
    end
endgenerate

// ==================================================================
// Rx comb
// ==================================================================
generate
    for (j = 0; j < 4; j = j + 1)
    begin : rx_comb
        always @(*)
        begin
            // default
            cnt_data_w[j] = 0;

            // Receiving
            if (rx_digitalreset_w == 1'b0 && rx_ready_w == 1'b1)
            begin
                if (phy_rx_enh_data_valid_w[j] == 1'b1) // Data valid
                begin
                    if (phy_rx_parallel_data_w[j] == phy_rx_parallel_data_r[j] + (j+1))
                        cnt_data_w[j] = cnt_data_r[j] + 1;
                end
                else
                begin
                    // 接收 IDLE 就keep
                    cnt_data_w[j] = cnt_data_r[j];
                end
            end
        end
    end
endgenerate



assign  LED[0] = cnt_ref_r[26];
assign  LED_BRACKET[0] = cnt_data_r[0][26];
assign  LED_BRACKET[1] = cnt_data_r[1][26];
assign  LED_BRACKET[2] = cnt_data_r[2][26];
assign  LED_BRACKET[3] = cnt_data_r[3][26];

endmodule
