
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module QSFP(

           //////////// CLOCK //////////
           input 		          		CLKUSR_100,
           input 		          		CLK_100_B3D,
           input 		          		CLK_50_B2J,
           input 		          		CLK_50_B2L,
           input 		          		CLK_50_B3D,
           input 		          		CLK_50_B3F,
           input 		          		CLK_50_B3H,

           //////////// KEY //////////
           input 		     [3:0]		BUTTON,
           input 		          		CPU_RESET_n,

           //////////// LED //////////
           output		     [3:0]		LED,
           output		     [3:0]		LED_BRACKET,

           //////////// SI5340A //////////
           output		          		SI5340A_I2C_SCL,
           inout 		          		SI5340A_I2C_SDA,
           input 		          		SI5340A_INTR,
           output		          		SI5340A_OE_n,
           output		          		SI5340A_RST_n,

           //////////// TPS40428 //////////
           input 		          		TPS40428_ALERT,
           output		          		TPS40428_CLK,
           inout 		          		TPS40428_DATA,

           //////////// QSFPA //////////
           input 		          		QSFPA_INTERRUPT_n,
           output		          		QSFPA_LP_MODE,
           input 		          		QSFPA_MOD_PRS_n,
           output		          		QSFPA_MOD_SEL_n,
           input 		          		QSFPA_REFCLK_p,
           output		          		QSFPA_RST_n,
           input 		     [3:0]		QSFPA_RX_p,
           output		          		QSFPA_SCL,
           inout 		          		QSFPA_SDA,
           output		     [3:0]		QSFPA_TX_p
       );



//=======================================================
//  REG/WIRE declarations
//=======================================================
assign QSFPA_LP_MODE = 1'b0;   // 關閉低功耗模式
assign QSFPA_MOD_SEL_n = 1'b0; // 選擇模組
assign QSFPA_RST_n = 1'b1;     // 解除重置



//=======================================================
//  Structural coding
//=======================================================




//=======================================================
//  Configure SI5340A
//=======================================================
`define SI5340A_POWER_DOWN  3'd0
`define SI5340A_644M53125   3'd1
`define SI5340A_322M265625  3'd2
`define SI5340A_312M5       3'd3
`define SI5340A_250M        3'd4
`define SI5340A_156M25      3'd5
`define SI5340A_125M        3'd6
`define SI5340A_100M        3'd7

wire si5340a_controller_start;
assign si5340a_controller_start = ~BUTTON[0];
wire si5340a_ready;
// 運作原理
// 用來「設定」外部那顆實體的 Silicon Labs Si5340A 時脈產生器晶片
// SI5340A 會產生 644.53125 MHz
// 這個 CLK = QSFPA_REFCLK_p 這個 port 進來, 之後要給 ATX PLL 當作參考時脈
si5340a_controller si5340a_controller(
                       .iCLK(CLK_50_B2J),
                       .iRST_n(CPU_RESET_n),
                       .iStart(si5340a_controller_start),
                       .iPLL_OUT0_FREQ_SEL(`SI5340A_644M53125),//QSFP-A
                       .iPLL_OUT1_FREQ_SEL(`SI5340A_POWER_DOWN),//QSFP-B
                       .iPLL_OUT2_FREQ_SEL(`SI5340A_POWER_DOWN),//QSFP-C
                       .iPLL_OUT3_FREQ_SEL(`SI5340A_POWER_DOWN),//QSFP-D
                       .I2C_CLK(SI5340A_I2C_SCL),
                       .I2C_DATA(SI5340A_I2C_SDA),
                       .oPLL_REG_CONFIG_DONE(si5340a_ready)     // 外部那顆實體的 Si5340A 晶片設定完成的訊號
                   );

assign SI5340A_OE_n = 1'b0;
assign SI5340A_RST_n = CPU_RESET_n;


// =======================================================
// ATX PLL
// =======================================================
wire global_reset_w = ~BUTTON[1] | ~si5340a_ready;
wire tx_serial_clk_w;
wire pll_locked_w;
ATX_PLL ATX_PLL (
            .pll_powerdown (1'b0),                  //i, 要打開 PLL
            .pll_refclk0   (QSFPA_REFCLK_p),        //i, 接   644.53125 MHz clk
            .tx_serial_clk (tx_serial_clk_w),       //o, 產生 5156.25 MHz 的 clk 給 PHY 用
            .pll_locked    (pll_locked_w),          //o
            .pll_cal_busy  ()                       //o
            // Reset Controller 必須等待 pll_cal_busy 降為 Low，且 pll_locked 升為 High，才會判定這個 PLL 真正可以開始工作
        );


// =======================================================
// PHY_RST
// =======================================================
wire tx_analogreset_w, tx_digitalreset_w;
wire rx_analogreset_w, rx_digitalreset_w;
wire tx_cal_busy_w, rx_cal_busy_w;
wire tx_ready_w, rx_ready_w;
wire rx_is_lockedtodata_w;
PHY_RST PHY_RST (
            .clock              (CLK_50_B2J),           // i, 使用基本clk (50MHz)
            .reset              (global_reset_w),       // i, 全域重置輸入，啟動重置流程
            .pll_powerdown      (),                     // o, 輸出給 ATX_PLL 的重置訊號
            .tx_analogreset     (tx_analogreset_w),     // o, 輸出給 PHY 發送端類比電路重置
            .tx_digitalreset    (tx_digitalreset_w),    // o, 輸出給 PHY 發送端數位電路重置
            .tx_ready           (tx_ready_w),                     // o, 通知系統：發送端已準備就緒
            .pll_locked         (pll_locked_w),         // i, 接收 ATX_PLL 的鎖定狀態
            .pll_select         (1'b0),                 // i, 選擇要監控哪一組 PLL (通常接常數)
            .tx_cal_busy        (tx_cal_busy_w),        // i, 接收 PHY 發送端的校準忙碌狀態
            .rx_analogreset     (rx_analogreset_w),     // o, 輸出給 PHY 接收端類比電路重置
            .rx_digitalreset    (rx_digitalreset_w),    // o, 輸出給 PHY 接收端數位電路重置
            .rx_ready           (rx_ready_w),                     // o, 通知系統：接收端已準備就緒
            .rx_is_lockedtodata (rx_is_lockedtodata_w), // i, 接收 PHY 的 CDR 資料鎖定狀態
            .rx_cal_busy        (rx_cal_busy_w)         // i, 接收 PHY 接收端的校準忙碌狀態
        );


// =======================================================
// PHY
// =======================================================
wire [3:0] phy_tx_cal_busy_w, phy_rx_cal_busy_w;
assign tx_cal_busy_w = |phy_tx_cal_busy_w; // 只要有任何一個通道在校準，就算整體發送端在校準
assign rx_cal_busy_w = |phy_rx_cal_busy_w;

wire [3:0] phy_rx_is_lockedtodata_w;
assign rx_is_lockedtodata_w = &phy_rx_is_lockedtodata_w; // 只有當所有通道的 CDR 都鎖定資料，才算整體接收端鎖定資料

wire [3:0] phy_tx_clkout_w, phy_rx_clkout_w;    // 除頻後的clk, 使用這個去接收 64bit 資料

reg [63:0] phy_tx_parallel_data_r[0:3], phy_tx_parallel_data_w[0:3];
reg [7:0] phy_tx_control_r[0:3], phy_tx_control_w[0:3];

wire [63:0] phy_rx_parallel_data_w[0:3]; // 平行資料, 這個給內部邏輯用
wire [7:0] phy_rx_control_w[0:3]; // RX 解碼出的控制字元狀態 (8'b00000000 表示全部都是資料)
reg [63:0] phy_rx_parallel_data_r[0:3];
reg [7:0] phy_rx_control_r[0:3];

PHY PHY (
        // ------------------------------------------
        // 接收端 (RX) 重置與校準訊號 (對接 PHY_RST)
        // ------------------------------------------
        .rx_analogreset_ch0      (rx_analogreset_w),            // i, RX 類比端重置
        .rx_analogreset_ch1      (rx_analogreset_w),            // i, RX 類比端重置
        .rx_analogreset_ch2      (rx_analogreset_w),            // i, RX 類比端重置
        .rx_analogreset_ch3      (rx_analogreset_w),            // i, RX 類比端重置
        .rx_cal_busy_ch0         (phy_rx_cal_busy_w[0]),        // o, RX 校準忙碌狀態
        .rx_cal_busy_ch1         (phy_rx_cal_busy_w[1]),        // o, RX 校準忙碌狀態
        .rx_cal_busy_ch2         (phy_rx_cal_busy_w[2]),        // o, RX 校準忙碌狀態
        .rx_cal_busy_ch3         (phy_rx_cal_busy_w[3]),        // o, RX 校準忙碌狀態

        // ------------------------------------------
        // 接收端 (RX) 時脈與鎖定狀態
        // ------------------------------------------
        .rx_cdr_refclk0          (QSFPA_REFCLK_p),              // i, CDR 參考時脈 接   644.53125 MHz clk
        .rx_clkout_ch0           (phy_rx_clkout_w[0]),                            // o, RX 復原後的除頻時脈 (156.25 MHz)
        .rx_clkout_ch1           (phy_rx_clkout_w[1]),                            // o, RX 復原後的除頻時脈 (156.25 MHz)
        .rx_clkout_ch2           (phy_rx_clkout_w[2]),                            // o, RX 復原後的除頻時脈 (156.25 MHz)
        .rx_clkout_ch3           (phy_rx_clkout_w[3]),                            // o, RX 復原後的除頻時脈 (156.25 MHz)
        .rx_coreclkin_ch0        (phy_rx_clkout_w[0]),                            // i, 驅動 RX 數位層的時脈 (接回 rx_clkout)
        .rx_coreclkin_ch1        (phy_rx_clkout_w[1]),                            // i, 驅動 RX 數位層的時脈 (接回 rx_clkout)
        .rx_coreclkin_ch2        (phy_rx_clkout_w[2]),                            // i, 驅動 RX 數位層的時脈 (接回 rx_clkout)
        .rx_coreclkin_ch3        (phy_rx_clkout_w[3]),                            // i, 驅動 RX 數位層的時脈 (接回 rx_clkout)
        .rx_digitalreset_ch0     (rx_digitalreset_w),           // i, RX 數位端重置
        .rx_digitalreset_ch1     (rx_digitalreset_w),           // i, RX 數位端重置
        .rx_digitalreset_ch2     (rx_digitalreset_w),           // i, RX 數位端重置
        .rx_digitalreset_ch3     (rx_digitalreset_w),           // i, RX 數位端重置
        .rx_is_lockedtodata_ch0  (phy_rx_is_lockedtodata_w[0]), // o, CDR 成功鎖定資料 (傳給 PHY_RST)
        .rx_is_lockedtodata_ch1  (phy_rx_is_lockedtodata_w[1]), // o, CDR 成功鎖定資料 (傳給 PHY_RST)
        .rx_is_lockedtodata_ch2  (phy_rx_is_lockedtodata_w[2]), // o, CDR 成功鎖定資料 (傳給 PHY_RST)
        .rx_is_lockedtodata_ch3  (phy_rx_is_lockedtodata_w[3]), // o, CDR 成功鎖定資料 (傳給 PHY_RST)
        .rx_is_lockedtoref_ch0   (),                            // o, CDR 鎖定參考時脈
        .rx_is_lockedtoref_ch1   (),                            // o, CDR 鎖定參考時脈
        .rx_is_lockedtoref_ch2   (),                            // o, CDR 鎖定參考時脈
        .rx_is_lockedtoref_ch3   (),                            // o, CDR 鎖定參考時脈

        // ------------------------------------------
        // 接收端 (RX) 資料 (序列與平行)
        // ------------------------------------------
        .rx_parallel_data_ch0    (phy_rx_parallel_data_w[0]),                            // o, [63:0] RX 解碼後的平行資料 (給內部邏輯)
        .rx_parallel_data_ch1    (phy_rx_parallel_data_w[1]),                            // o, [63:0] RX 解碼後的平行資料 (給內部邏輯)
        .rx_parallel_data_ch2    (phy_rx_parallel_data_w[2]),                            // o, [63:0] RX 解碼後的平行資料 (給內部邏輯)
        .rx_parallel_data_ch3    (phy_rx_parallel_data_w[3]),                            // o, [63:0] RX 解碼後的平行資料 (給內部邏輯)
        .rx_serial_data_ch0      (QSFPA_RX_p[0]),               // i, RX 高速光通訊序列輸入 (10.3125 Gbps)
        .rx_serial_data_ch1      (QSFPA_RX_p[1]),               // i, RX 高速光通訊序列輸入 (10.3125 Gbps)
        .rx_serial_data_ch2      (QSFPA_RX_p[2]),               // i, RX 高速光通訊序列輸入 (10.3125 Gbps)
        .rx_serial_data_ch3      (QSFPA_RX_p[3]),               // i, RX 高速光通訊序列輸入 (10.3125 Gbps)

        // ------------------------------------------
        // 發送端 (TX) 重置與校準訊號 (對接 PHY_RST)
        // ------------------------------------------
        .tx_analogreset_ch0      (tx_analogreset_w),            // i, TX 類比端重置
        .tx_analogreset_ch1      (tx_analogreset_w),            // i, TX 類比端重置
        .tx_analogreset_ch2      (tx_analogreset_w),            // i, TX 類比端重置
        .tx_analogreset_ch3      (tx_analogreset_w),            // i, TX 類比端重置
        .tx_cal_busy_ch0         (phy_tx_cal_busy_w[0]),        // o, TX 校準忙碌狀態
        .tx_cal_busy_ch1         (phy_tx_cal_busy_w[1]),        // o, TX 校準忙碌狀態
        .tx_cal_busy_ch2         (phy_tx_cal_busy_w[2]),        // o, TX 校準忙碌狀態
        .tx_cal_busy_ch3         (phy_tx_cal_busy_w[3]),        // o, TX 校準忙碌狀態

        // ------------------------------------------
        // 發送端 (TX) 時脈
        // ------------------------------------------
        .tx_clkout_ch0           (phy_tx_clkout_w[0]),                            // o, TX 除頻輸出時脈 (156.25 MHz)
        .tx_clkout_ch1           (phy_tx_clkout_w[1]),                            // o, TX 除頻輸出時脈 (156.25 MHz)
        .tx_clkout_ch2           (phy_tx_clkout_w[2]),                            // o, TX 除頻輸出時脈 (156.25 MHz)
        .tx_clkout_ch3           (phy_tx_clkout_w[3]),                            // o, TX 除頻輸出時脈 (156.25 MHz)
        .tx_coreclkin_ch0        (phy_tx_clkout_w[0]),                            // i, 驅動 TX 數位層的時脈 (通常接回 tx_clkout)
        .tx_coreclkin_ch1        (phy_tx_clkout_w[1]),                            // i, 驅動 TX 數位層的時脈 (通常接回 tx_clkout)
        .tx_coreclkin_ch2        (phy_tx_clkout_w[2]),                            // i, 驅動 TX 數位層的時脈 (通常接回 tx_clkout)
        .tx_coreclkin_ch3        (phy_tx_clkout_w[3]),                            // i, 驅動 TX 數位層的時脈 (通常接回 tx_clkout)
        .tx_digitalreset_ch0     (tx_digitalreset_w),           // i, TX 數位端重置
        .tx_digitalreset_ch1     (tx_digitalreset_w),           // i, TX 數位端重置
        .tx_digitalreset_ch2     (tx_digitalreset_w),           // i, TX 數位端重置
        .tx_digitalreset_ch3     (tx_digitalreset_w),           // i, TX 數位端重置

        // ------------------------------------------
        // 發送端 (TX) 資料 (平行與序列)
        // ------------------------------------------
        .tx_parallel_data_ch0    (phy_tx_parallel_data_r[0]),                            // i, [63:0] TX 準備發送的平行資料 (來自內部邏輯)
        .tx_parallel_data_ch1    (phy_tx_parallel_data_r[1]),                            // i, [63:0] TX 準備發送的平行資料 (來自內部邏輯)
        .tx_parallel_data_ch2    (phy_tx_parallel_data_r[2]),                            // i, [63:0] TX 準備發送的平行資料 (來自內部邏輯)
        .tx_parallel_data_ch3    (phy_tx_parallel_data_r[3]),                            // i, [63:0] TX 準備發送的平行資料 (來自內部邏輯)
        .tx_serial_clk0_ch0      (tx_serial_clk_w),             // i, 來自 ATX_PLL 的高速時脈 (5.156 GHz)
        .tx_serial_clk0_ch1      (tx_serial_clk_w),             // i, 來自 ATX_PLL 的高速時脈 (5.156 GHz)
        .tx_serial_clk0_ch2      (tx_serial_clk_w),             // i, 來自 ATX_PLL 的高速時脈 (5.156 GHz)
        .tx_serial_clk0_ch3      (tx_serial_clk_w),             // i, 來自 ATX_PLL 的高速時脈 (5.156 GHz)
        .tx_serial_data_ch0      (QSFPA_TX_p[0]),               // o, TX 高速光通訊序列輸出 (10.3125 Gbps)
        .tx_serial_data_ch1      (QSFPA_TX_p[1]),               // o, TX 高速光通訊序列輸出 (10.3125 Gbps)
        .tx_serial_data_ch2      (QSFPA_TX_p[2]),               // o, TX 高速光通訊序列輸出 (10.3125 Gbps)
        .tx_serial_data_ch3      (QSFPA_TX_p[3]),               // o, TX 高速光通訊序列輸出 (10.3125 Gbps)

        // ------------------------------------------
        // 未使用腳位與 10GBASE-R 專用控制訊號
        // ------------------------------------------
        .unused_rx_parallel_data (),                            // o, [255:0] 預留的未使用 RX 寬度
        .unused_tx_parallel_data (),                            // i, [255:0] 預留的未使用 TX 寬度
        .tx_enh_data_valid_ch0   (1'b1),                            // i, Data Valid，拉高(1)時 TX 才會把資料打出去
        .tx_enh_data_valid_ch1   (1'b1),                            // i, Data Valid，拉高(1)時 TX 才會把資料打出去
        .tx_enh_data_valid_ch2   (1'b1),                            // i, Data Valid，拉高(1)時 TX 才會把資料打出去
        .tx_enh_data_valid_ch3   (1'b1),                            // i, Data Valid，拉高(1)時 TX 才會把資料打出去
        .tx_control_ch0          (phy_tx_control_r[0]),             // i, [7:0] TX 控制字元 (8'b00000000 表示全部都是資料, 8'b00000001 表示第 0 個 byte 是控制字元)
        .tx_err_ins_ch0          (1'b0),                            // i, 錯誤注入測試腳位 (通常接 0)
        .tx_control_ch1          (phy_tx_control_r[0]),             // i, [7:0] TX 控制字元
        .tx_err_ins_ch1          (1'b0),                            // i, 錯誤注入測試腳位
        .tx_control_ch2          (phy_tx_control_r[0]),             // i, [7:0] TX 控制字元
        .tx_err_ins_ch2          (1'b0),                            // i, 錯誤注入測試腳位
        .tx_control_ch3          (phy_tx_control_r[0]),             // i, [7:0] TX 控制字元
        .tx_err_ins_ch3          (1'b0),                            // i, 錯誤注入測試腳位
        .unused_tx_control       (),                            // i, [35:0] 預留的未使用 TX 控制訊號
        .rx_control_ch0          (phy_rx_control_w[0]),                            // o, [7:0] RX 解碼出的控制字元狀態
        .rx_control_ch1          (phy_rx_control_w[1]),                            // o, [7:0] RX 解碼出的控制字元狀態
        .rx_control_ch2          (phy_rx_control_w[2]),                            // o, [7:0] RX 解碼出的控制字元狀態
        .rx_control_ch3          (phy_rx_control_w[3]),                            // o, [7:0] RX 解碼出的控制字元狀態
        .unused_rx_control       (),                             // o, [47:0] 預留的未使用 RX 控制訊號
        .rx_seriallpbken_ch0     (1'b1),
        .rx_seriallpbken_ch1     (1'b1),
        .rx_seriallpbken_ch2     (1'b1),
        .rx_seriallpbken_ch3     (1'b1)
    );



// =======================================================
// Test Logic - Sequential
// =======================================================
reg [3:0] tx_cnt_w, tx_cnt_r;
reg [25:0] correct_cnt_w, correct_cnt_r;
reg [25:0] ref_cnt_w, ref_cnt_r;
// =======================================================
// 發送端 (TX) 循序邏輯 - 嚴格使用 tx_clkout 與 tx_digitalreset
// =======================================================
always @(posedge phy_tx_clkout_w[0] or posedge tx_digitalreset_w)
begin
    if (tx_digitalreset_w)
    begin
        tx_cnt_r <= 8'd0; // 計數器跟著 ch0 走即可
        phy_tx_parallel_data_r[0] <= 64'b0;
        phy_tx_control_r[0] <= 8'b0;
    end
    else
    begin
        tx_cnt_r <= tx_cnt_w;
        phy_tx_parallel_data_r[0] <= phy_tx_parallel_data_w[0];
        phy_tx_control_r[0] <= phy_tx_control_w[0];
    end
end
always @(posedge phy_tx_clkout_w[1] or posedge tx_digitalreset_w)
begin
    if (tx_digitalreset_w)
    begin
        phy_tx_parallel_data_r[1] <= 64'b0;
        phy_tx_control_r[1] <= 8'b0;
    end
    else
    begin
        phy_tx_parallel_data_r[1] <= phy_tx_parallel_data_w[1];
        phy_tx_control_r[1] <= phy_tx_control_w[1];
    end
end
always @(posedge phy_tx_clkout_w[2] or posedge tx_digitalreset_w)
begin
    if (tx_digitalreset_w)
    begin
        phy_tx_parallel_data_r[2] <= 64'b0;
        phy_tx_control_r[2] <= 8'b0;
    end
    else
    begin
        phy_tx_parallel_data_r[2] <= phy_tx_parallel_data_w[2];
        phy_tx_control_r[2] <= phy_tx_control_w[2];
    end
end
always @(posedge phy_tx_clkout_w[3] or posedge tx_digitalreset_w)
begin
    if (tx_digitalreset_w)
    begin
        phy_tx_parallel_data_r[3] <= 64'b0;
        phy_tx_control_r[3] <= 8'b0;
    end
    else
    begin
        phy_tx_parallel_data_r[3] <= phy_tx_parallel_data_w[3];
        phy_tx_control_r[3] <= phy_tx_control_w[3];
    end
end

// =======================================================
// 接收端 (RX) 循序邏輯 - 嚴格使用 rx_clkout 與 rx_digitalreset
// =======================================================
always @(posedge phy_rx_clkout_w[0] or posedge rx_digitalreset_w)
begin
    if (rx_digitalreset_w)
    begin
        correct_cnt_r <= 26'd0;
        ref_cnt_r <= 26'd0;
        phy_rx_parallel_data_r[0] <= 64'b0;
        phy_rx_control_r[0] <= 8'b0;
    end
    else
    begin
        correct_cnt_r <= correct_cnt_w;
        ref_cnt_r <= ref_cnt_w;
        phy_rx_parallel_data_r[0] <= phy_rx_parallel_data_w[0];
        phy_rx_control_r[0] <= phy_rx_control_w[0];
    end
end
always @(posedge phy_rx_clkout_w[1] or posedge rx_digitalreset_w)
begin
    if (rx_digitalreset_w)
    begin
        phy_rx_parallel_data_r[1] <= 64'b0;
        phy_rx_control_r[1] <= 8'b0;
    end
    else
    begin
        phy_rx_parallel_data_r[1] <= phy_rx_parallel_data_w[1];
        phy_rx_control_r[1] <= phy_rx_control_w[1];
    end
end
always @(posedge phy_rx_clkout_w[2] or posedge rx_digitalreset_w)
begin
    if (rx_digitalreset_w)
    begin
        phy_rx_parallel_data_r[2] <= 64'b0;
        phy_rx_control_r[2] <= 8'b0;
    end
    else
    begin
        phy_rx_parallel_data_r[2] <= phy_rx_parallel_data_w[2];
        phy_rx_control_r[2] <= phy_rx_control_w[2];
    end
end
always @(posedge phy_rx_clkout_w[3] or posedge rx_digitalreset_w)
begin
    if (rx_digitalreset_w)
    begin
        phy_rx_parallel_data_r[3] <= 64'b0;
        phy_rx_control_r[3] <= 8'b0;
    end
    else
    begin
        phy_rx_parallel_data_r[3] <= phy_rx_parallel_data_w[3];
        phy_rx_control_r[3] <= phy_rx_control_w[3];
    end
end

// =======================================================
// Test Logic - Combinational
// =======================================================
always @(*)
begin
    // --------------
    // default assignment
    // --------------
    tx_cnt_w = tx_cnt_r;
    phy_tx_parallel_data_w[0] = phy_tx_parallel_data_r[0];
    phy_tx_parallel_data_w[1] = phy_tx_parallel_data_r[1];
    phy_tx_parallel_data_w[2] = phy_tx_parallel_data_r[2];
    phy_tx_parallel_data_w[3] = phy_tx_parallel_data_r[3];
    phy_tx_control_w[0] = 0;
    phy_tx_control_w[1] = 0;
    phy_tx_control_w[2] = 0;
    phy_tx_control_w[3] = 0;

    // --------------
    // Test Pattern: 加上 10GBASE-R 標準的 Start 與 Terminate 框架
    // --------------
    if (tx_digitalreset_w || ~tx_ready_w)
    begin
        // 傳送 IDLE 字元 (0x07) 給所有通道
        phy_tx_parallel_data_w[0] = 64'h0707_0707_0707_0707;
        phy_tx_parallel_data_w[1] = 64'h0707_0707_0707_0707;
        phy_tx_parallel_data_w[2] = 64'h0707_0707_0707_0707;
        phy_tx_parallel_data_w[3] = 64'h0707_0707_0707_0707;
        phy_tx_control_w[0] = 8'hFF;
        phy_tx_control_w[1] = 8'hFF;
        phy_tx_control_w[2] = 8'hFF;
        phy_tx_control_w[3] = 8'hFF;
    end
    else
    begin
        tx_cnt_w = tx_cnt_r + 1;

        if (tx_cnt_r == 0)
        begin
            // 【封包起點】: 發送 Start 字元 (0xFB) 於 Byte 0
            // 注意最低位元組改為 FB，這樣 PCS 才知道資料要開始了
            phy_tx_parallel_data_w[0] = 64'h0000_5678_9ABC_DEFB;
            phy_tx_parallel_data_w[1] = 64'h1234_0000_9ABC_DEFB;
            phy_tx_parallel_data_w[2] = 64'h1234_5678_0000_DEFB;
            phy_tx_parallel_data_w[3] = 64'h1234_5678_9ABC_00FB;
            // 只有 Byte 0 是控制字元，所以 Control = 8'h01
            phy_tx_control_w[0] = 8'h01;
            phy_tx_control_w[1] = 8'h01;
            phy_tx_control_w[2] = 8'h01;
            phy_tx_control_w[3] = 8'h01;
        end
        else if (tx_cnt_r == 14)
        begin
            // 【封包終點】: 發送 Terminate 字元 (0xFD) 於 Byte 0，後面補 IDLE
            phy_tx_parallel_data_w[0] = 64'h0707_0707_0707_07FD;
            phy_tx_parallel_data_w[1] = 64'h0707_0707_0707_07FD;
            phy_tx_parallel_data_w[2] = 64'h0707_0707_0707_07FD;
            phy_tx_parallel_data_w[3] = 64'h0707_0707_0707_07FD;
            // 包含 FD 與後續的 07 都是控制字元，所以 Control = 8'hFF
            phy_tx_control_w[0] = 8'hFF;
            phy_tx_control_w[1] = 8'hFF;
            phy_tx_control_w[2] = 8'hFF;
            phy_tx_control_w[3] = 8'hFF;
        end
        else if (tx_cnt_r == 15)
        begin
            // 【封包間隔】: 傳送全 IDLE 字元 (0x07)
            phy_tx_parallel_data_w[0] = 64'h0707_0707_0707_0707;
            phy_tx_parallel_data_w[1] = 64'h0707_0707_0707_0707;
            phy_tx_parallel_data_w[2] = 64'h0707_0707_0707_0707;
            phy_tx_parallel_data_w[3] = 64'h0707_0707_0707_0707;
            phy_tx_control_w[0] = 8'hFF;
            phy_tx_control_w[1] = 8'hFF;
            phy_tx_control_w[2] = 8'hFF;
            phy_tx_control_w[3] = 8'hFF;
        end
        else
        begin
            // 【正常資料】: 傳送你的 Payload
            phy_tx_parallel_data_w[0] = 64'h0000_5678_9ABC_DEFF;
            phy_tx_parallel_data_w[1] = 64'h1234_0000_9ABC_DEFF;
            phy_tx_parallel_data_w[2] = 64'h1234_5678_0000_DEFF;
            phy_tx_parallel_data_w[3] = 64'h1234_5678_9ABC_0000;
            // 全部都是 Data，Control = 8'h00
            phy_tx_control_w[0] = 8'h00;
            phy_tx_control_w[1] = 8'h00;
            phy_tx_control_w[2] = 8'h00;
            phy_tx_control_w[3] = 8'h00;
        end
    end
end

// =======================================================
// Test Logic - Combinational - 接收邏輯
// =======================================================
always @(*)
begin
    //------------------------
    // default assignment
    //------------------------
    correct_cnt_w = correct_cnt_r;
    ref_cnt_w = ref_cnt_r + 1;

    //------------------------
    // 接收
    //------------------------
    if (phy_rx_control_r[0] == 8'h00)
    begin
        if (phy_rx_parallel_data_r[0] == 64'h0000_5678_9ABC_DEFF)
            correct_cnt_w = correct_cnt_r + 1;
        else
            correct_cnt_w = 0;
    end
end

assign LED[0] =  ref_cnt_r[25];
assign LED[1] =  correct_cnt_r[25];

endmodule
