//=======================================================
//  This code is generated by Terasic System Builder (Modified)
//=======================================================

module QSFP_TX_RX(

           //////////// CLOCK //////////
           input                        CLKUSR_100,
           input                        CLK_100_B3D,
           input                        CLK_50_B2J,
           input                        CLK_50_B2L,
           input                        CLK_50_B3D,
           input                        CLK_50_B3F,
           input                        CLK_50_B3H,

           //////////// KEY //////////
           input             [3:0]      BUTTON,
           input                        CPU_RESET_n,

           //////////// SW //////////
           input             [1:0]      SW,

           //////////// LED //////////
           output            [3:0]      LED,
           output            [3:0]      LED_BRACKET,

           //////////// SEG7 //////////
           output                       HEX0_DP,
           output            [6:0]      HEX0_D,
           output                       HEX1_DP,
           output            [6:0]      HEX1_D,

           //////////// FAN //////////
           input                        FAN_ALERT_n,
           output                       FAN_I2C_SCL,
           inout                        FAN_I2C_SDA,

           //////////// SI5340A //////////
           output                       SI5340A_I2C_SCL,
           inout                        SI5340A_I2C_SDA,
           input                        SI5340A_INTR,
           output                       SI5340A_OE_n,
           output                       SI5340A_RST_n,

           //////////// SI5340B //////////
           output                       SI5340B_I2C_SCL,
           inout                        SI5340B_I2C_SDA,
           input                        SI5340B_INTR,
           output                       SI5340B_OE_n,
           output                       SI5340B_RST_n,

           //////////// TPS40428 //////////
           input                        TPS40428_ALERT,
           output                       TPS40428_CLK,
           inout                        TPS40428_DATA,

           //////////// Temperature //////////
           output                       TEMP_I2C_SCL,
           inout                        TEMP_I2C_SDA,
           input                        TEMP_INT_n,
           input                        TEMP_OVERT_n,

           //////////// POWER Monitor //////////
           input                        POWER_MONITOR_ALERT,
           output                       POWER_MONITOR_I2C_SCL,
           inout                        POWER_MONITOR_I2C_SDA,

           //////////// PCIE //////////
           input                        PCIE_PERST_n,
           input                        PCIE_REFCLK_p,
           input             [7:0]      PCIE_RX_p,
           input                        PCIE_SMBCLK,
           inout                        PCIE_SMBDAT,
           output            [7:0]      PCIE_TX_p,
           output                       PCIE_WAKE_n,

           //////////// PCIe On-Board Ref Clock //////////
           input                        OB_PCIE_REFCLK_p,

           //////////// QSFPA //////////
           input                        QSFPA_INTERRUPT_n,
           output                       QSFPA_LP_MODE,
           input                        QSFPA_MOD_PRS_n,
           output                       QSFPA_MOD_SEL_n,
           input                        QSFPA_REFCLK_p,
           output                       QSFPA_RST_n,
           input             [3:0]      QSFPA_RX_p,
           output                       QSFPA_SCL,
           inout                        QSFPA_SDA,
           output            [3:0]      QSFPA_TX_p
       );


//=======================================================
//  解決 Warning: 賦予未使用的腳位預設安全值
//=======================================================
// 根據 DE5a-Net 規格，LED 為 Active Low (低電位亮，高電位暗)
assign HEX0_D = 7'b1111111;   // 關閉七段顯示器
assign HEX1_D = 7'b1111111;
assign HEX0_DP = 1'b1;
assign HEX1_DP = 1'b1;

// 消除 "Bidirectional pins have no drivers" 的警告，將未用到的 I2C 設定為高阻抗 (z)
assign FAN_I2C_SCL = 1'bz;
assign FAN_I2C_SDA = 1'bz;
assign TPS40428_CLK = 1'bz;
assign TPS40428_DATA = 1'bz;
assign TEMP_I2C_SCL = 1'bz;
assign TEMP_I2C_SDA = 1'bz;
assign POWER_MONITOR_I2C_SCL = 1'bz;
assign POWER_MONITOR_I2C_SDA = 1'bz;
assign PCIE_SMBDAT = 1'bz;
assign QSFPA_SCL = 1'bz;
assign QSFPA_SDA = 1'bz;

// 未用到的 PCIe 輸出腳位
assign PCIE_TX_p = 8'd0;
assign PCIE_WAKE_n = 1'b1;

// QSFP+ 控制腳位預設值
assign QSFPA_LP_MODE = 1'b0;   // 關閉低功耗模式
assign QSFPA_MOD_SEL_n = 1'b0; // 選擇模組
assign QSFPA_RST_n = 1'b1;     // 解除重置

//=======================================================
//  Configure SI5340A (設定為 644.53125 MHz)
//=======================================================
`define SI5340A_POWER_DOWN  3'd0
`define SI5340A_644M53125   3'd1
`define SI5340A_322M265625  3'd2
`define SI5340A_312M5       3'd3
`define SI5340A_250M        3'd4
`define SI5340A_156M25      3'd5
`define SI5340A_125M        3'd6
`define SI5340A_100M        3'd7

wire si5340a_controller_start;
assign si5340a_controller_start = ~BUTTON[0];

wire si5340a_ready;

si5340a_controller si5340a_controller(
                       .iCLK(CLK_50_B2J),
                       .iRST_n(CPU_RESET_n),
                       .iStart(si5340a_controller_start),
                       .iPLL_OUT0_FREQ_SEL(`SI5340A_644M53125), // QSFP-A 使用 644.53125 MHz
                       .iPLL_OUT1_FREQ_SEL(`SI5340A_POWER_DOWN),
                       .iPLL_OUT2_FREQ_SEL(`SI5340A_POWER_DOWN),
                       .iPLL_OUT3_FREQ_SEL(`SI5340A_POWER_DOWN),
                       .I2C_CLK(SI5340A_I2C_SCL),
                       .I2C_DATA(SI5340A_I2C_SDA),
                       .oPLL_REG_CONFIG_DONE(si5340a_ready)     // 輸出準備好的訊號，非常重要
                   );

assign SI5340A_OE_n = 1'b0;
assign SI5340A_RST_n = CPU_RESET_n;

//=======================================================
//  Configure SI5340B (PCIe / DDR 時脈)
//=======================================================
`define DDR300_QDR275_PCIE100   5'd0
`define DDR266_QDR275_PCIE100   5'd1
wire si5340b_controller_start;
wire config_done;

assign si5340b_controller_start = ~BUTTON[0];

si5340b_controller si5340b_controller(
                       .iCLK(CLK_50_B2J),
                       .iRST_n(CPU_RESET_n),
                       .iStart(si5340b_controller_start),
                       .iPLL_OUT_FREQ_SEL(`DDR266_QDR275_PCIE100),
                       .I2C_CLK(SI5340B_I2C_SCL),
                       .I2C_DATA(SI5340B_I2C_SDA),
                       .oPLL_REG_CONFIG_DONE(config_done)
                   );

assign SI5340B_OE_n = 1'b0;
assign SI5340B_RST_n = CPU_RESET_n;

// =========================================================
// 內部連線與 IP 實例化 (簡化 16-bit 介面)
// =========================================================
wire tx_serial_clk;
wire pll_locked;
wire tx_cal_busy, rx_cal_busy;
wire rx_is_lockedtodata;
wire tx_analogreset, rx_analogreset;
wire tx_digitalreset, rx_digitalreset;
wire tx_ready, rx_ready;
wire tx_clkout, rx_clkout;

// 總重置訊號：結合了 BUTTON[1] 按鈕以及 Si5340A 的準備狀態
wire global_reset;
assign global_reset = ~BUTTON[1] | ~si5340a_ready;

// --- 實例化 ATX PLL ---
Transceiver_ATX_PLL u_pll (
                        .pll_powerdown   (1'b0),
                        .pll_refclk0     (QSFPA_REFCLK_p),
                        .tx_serial_clk   (tx_serial_clk),
                        .pll_locked      (pll_locked),
                        .pll_cal_busy    (),
                        .mcgb_rst        (1'b0),
                        .mcgb_serial_clk ()
                    );

// --- 實例化 Reset Controller ---
PHY_Reset_Controller u_reset (
                         .clock              (CLK_50_B3D),
                         .reset              (global_reset),
                         .pll_powerdown      (),
                         .tx_analogreset     (tx_analogreset),
                         .tx_digitalreset    (tx_digitalreset),
                         .tx_ready           (tx_ready),
                         .pll_locked         (pll_locked),
                         .pll_select         (1'b0),
                         .tx_cal_busy        (tx_cal_busy),
                         .rx_analogreset     (rx_analogreset),
                         .rx_digitalreset    (rx_digitalreset),
                         .rx_ready           (rx_ready),
                         .rx_is_lockedtodata (rx_is_lockedtodata),
                         .rx_cal_busy        (rx_cal_busy)
                     );

// =========================================================
//  常數傳送邏輯 (修正版：定期發送 K28.5 確保對齊)
// =========================================================

reg [15:0] tx_align_counter = 0;
reg [15:0] tx_data_reg;
reg [1:0]  tx_datak_reg;

always @(posedge tx_clkout or posedge tx_digitalreset)
begin
    if (tx_digitalreset)
    begin
        tx_align_counter <= 16'd0;
        tx_data_reg <= 16'hBCBC;
        tx_datak_reg <= 2'b11;
    end
    else
    begin
        tx_align_counter <= tx_align_counter + 16'd1;
        // 這樣等於連續發送 K28.5，絕對滿足接收端 "achieve sync: 3" 的要求！
        // 改變條件：每 256 個週期中，抽出「前 10 個週期」來發送標準 Idle 序列
        if (tx_align_counter[7:0] < 8'd10)
        begin
            // 傳送標準 Idle 序列: BC (K28.5)
            tx_data_reg <= 16'hBCBC;
            tx_datak_reg <= 2'b11; 
        end
        else
        begin
            tx_data_reg <= 16'h5A5A; // 資料
            tx_datak_reg <= 2'b00;   // 純資料
        end
    end
end

// --- 實例化新版 Native PHY (簡化介面) ---
// =========================================================
// 4通道 PHY 專用線路宣告
// =========================================================
wire [3:0] phy_tx_clkout;
wire [3:0] phy_rx_clkout;
wire [3:0] phy_tx_cal_busy;
wire [3:0] phy_rx_cal_busy;
wire [3:0] phy_rx_is_lockedtodata;

wire [63:0] phy_rx_parallel_data;
wire [7:0]  phy_rx_datak;
wire [7:0]  phy_rx_syncstatus;
wire [7:0]  phy_rx_disperr;
wire [7:0]  phy_rx_errdetect;

// 1. Reset 訊號扇出 (Fan-out)：將 1 個重置訊號複製給 4 個通道
wire [3:0] phy_tx_analogreset  = {4{tx_analogreset}};
wire [3:0] phy_tx_digitalreset = {4{tx_digitalreset}};
wire [3:0] phy_rx_analogreset  = {4{rx_analogreset}};
wire [3:0] phy_rx_digitalreset = {4{rx_digitalreset}};

// 2. 狀態訊號聚合 (Fan-in)：用 OR 邏輯回傳給單通道的 Reset Controller
// 只要有任一通道還在校準，就回報 busy；只要有任一通道抓到光訊號，就允許進行後續重置
assign tx_cal_busy = |phy_tx_cal_busy;
assign rx_cal_busy = |phy_rx_cal_busy;
assign rx_is_lockedtodata = |phy_rx_is_lockedtodata;

// 3. 全局時脈：統一借用 Channel 0 的時脈來推動你的 LED 和 TX Data 產生器
assign tx_clkout = phy_tx_clkout[0];
assign rx_clkout = phy_rx_clkout[0];

// =========================================================
// 實例化 4 通道 Native PHY
// =========================================================
Transceiver_Native_PHY u_phy (
                           .tx_analogreset          (phy_tx_analogreset),
                           .tx_digitalreset         (phy_tx_digitalreset),
                           .rx_analogreset          (phy_rx_analogreset),
                           .rx_digitalreset         (phy_rx_digitalreset),

                           .tx_cal_busy             (phy_tx_cal_busy),
                           .rx_cal_busy             (phy_rx_cal_busy),

                           // 時脈繞接：PLL 輸出的 tx_serial_clk 複製給 4 個通道
                           .tx_serial_clk0          ({4{tx_serial_clk}}),
                           .rx_cdr_refclk0          (QSFPA_REFCLK_p),

                           // === 實體光纖腳位全開 ===
                           .tx_serial_data          (QSFPA_TX_p[3:0]),
                           .rx_serial_data          (QSFPA_RX_p[3:0]),

                           .rx_is_lockedtoref       (),
                           .rx_is_lockedtodata      (phy_rx_is_lockedtodata),

                           // Core Clock 繞接：將每個通道各自的 clkout 接回自己的 coreclkin
                           .tx_coreclkin            (phy_tx_clkout),
                           .rx_coreclkin            (phy_rx_clkout),
                           .tx_clkout               (phy_tx_clkout),
                           .rx_clkout               (phy_rx_clkout),

                           // === TX 廣播模式：把你的 tx_data_reg 複製 4 份同時送出 ===
                           .tx_parallel_data        ({4{tx_data_reg}}),
                           .tx_datak                ({4{tx_datak_reg}}),
                           .unused_tx_parallel_data (440'd0),

                           // === RX 接收陣列 (接進我們宣告的寬排線) ===
                           .rx_parallel_data        (phy_rx_parallel_data),
                           .rx_datak                (phy_rx_datak),
                           .rx_syncstatus           (phy_rx_syncstatus),
                           .rx_disperr              (phy_rx_disperr),
                           .rx_errdetect            (phy_rx_errdetect),
                           .rx_patterndetect        (),
                           .rx_runningdisp          (),
                           .unused_rx_parallel_data (),

                           // ===============================
                           // 控制與極性
                           // ===============================
                           // 先全部給 0。如果全沒抓到，可以改成 4'b1111 試試反相
                           .rx_polinv               (4'b0000),

                           // 關閉內部迴圈測試，準備實戰
                           .rx_seriallpbken         (4'b0000)
                       );

// =========================================================
//  接收端 LED 閃爍驗證邏輯 (修正版：包容 K28.5)
// =========================================================

reg [26:0] rx_led_counter;
reg [26:0] counter_r;

always @(posedge rx_clkout or posedge rx_digitalreset)
begin
    if (rx_digitalreset)
    begin
        rx_led_counter <= 27'd0;
        counter_r <= 27'd0;
    end
    else
    begin
        // 條件：必須同步 且 沒有任何錯誤
        if (phy_rx_syncstatus[1:0] == 2'b11 &&
                phy_rx_disperr[1:0] == 2'b00 &&
                phy_rx_errdetect[1:0] == 2'b00)
        begin
            // 允許收到 5A5A (資料) 或 BCBC (控制字元)
            if ((phy_rx_datak[1:0] == 2'b00 && phy_rx_parallel_data[15:0] == 16'h5A5A) ||
                    (phy_rx_datak[1:0] == 2'b11 && phy_rx_parallel_data[15:0] == 16'hBCBC))
            begin
                rx_led_counter <= rx_led_counter + 27'd1;
            end
            else
            begin
                rx_led_counter <= 27'd0; // 收到預期外的雜訊資料，歸零
            end
        end
        else
        begin
            rx_led_counter <= 27'd0; // 失步或底層錯誤，歸零
        end

        counter_r <= counter_r + 27'd1;
    end
end

// LED[0] 表示連線與資料接收狀態：正常收 5A5A 時會閃爍，出錯時會常暗
assign LED[0] = ~(rx_led_counter[26]);

// LED[1] 是一個單純的 heartbeat，用來確認 rx_clkout 有在正常震盪
assign LED[1] = counter_r[26];


assign LED_BRACKET = LED; // 直接將 LED 的狀態反映到 LED_BRACKET 上，方便觀察
endmodule
